/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1RG7ZdGdozX
 */
import Link from "next/link"

export function Footer() {
  return (
    <footer className="fixed bottom-0 w-full h-12 flex items-center justify-center bg-gray-800 px-4 md:px-6">
      <div className="flex gap-4">
        <Link href="#">
          <FacebookIcon className="h-6 w-6 text-white" />
          <span className="sr-only">Facebook</span>
        </Link>
        <Link href="#">
          <TwitterIcon className="h-6 w-6 text-white" />
          <span className="sr-only">Twitter</span>
        </Link>
        <Link href="#">
          <InstagramIcon className="h-6 w-6 text-white" />
          <span className="sr-only">Instagram</span>
        </Link>
      </div>
      <p className="text-xs text-white ml-auto">© 2024 Acme Inc. All rights reserved.</p>
      <Link className="text-xs text-white underline underline-offset-2 ml-4" href="#">
        Privacy
      </Link>
    </footer>
  )
}


function FacebookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 1-1h3z" />
    </svg>
  )
}


function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function InstagramIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 12.63 8 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}
